FROM python:3.8.17-slim

RUN apt-get update && apt-get install -y \
    build-essential

RUN pip install --upgrade pip

RUN useradd -ms /bin/bash seyed
WORKDIR /home/code

COPY lint-requirements.txt /home/code/
RUN pip install --no-cache-dir -r lint-requirements.txt

COPY . /home/code/

USER seyed